#!/usr/bin/env node
// brand-js — the theme's colours, resolved, for code that cannot read a CSS variable.
//
// Component CSS and inline styles read `var(--token)` and follow a re-skin on their own. Some code
// cannot: the quote and inspection-report templates (HTML strings the browser prints and the server
// renders to PDF), the server's emails and public pages, canvas drawing, generated SVG. Those read
// BRAND from src/brand/tokens.generated.js, which this script writes from the live theme cascade
// (theme.css → theme-<client>.css → theme-flat.css → index.css :root), so the theme stays the one
// source of every colour. test-design-system.mjs fails when the file no longer matches the cascade.
//
//   npm --prefix app run brand:js          (write)
//   node scripts/brand-js.mjs --check      (exit 1 when stale; what the gate runs)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { APP, readCascade } from './design-system-lib.mjs';

export const OUT = path.join(APP, 'src', 'brand', 'tokens.generated.js');

// role → the theme token that means it. Grouped the way a template reaches for them.
export const ROLES = {
  // the brand
  primary: 'primary', // headings on documents, bands, primary buttons (brand ink)
  primaryDeep: 'primary-deep',
  primarySoft: 'primary-soft',
  primaryBg: 'primary-bg',
  onPrimary: 'color-text-on-primary', // text on a primary fill
  accent: 'color-brand-secondary-500', // the CTA / highlight colour
  accentHover: 'color-brand-secondary-600',
  accentSoft: 'color-brand-secondary-100',
  accentBg: 'color-brand-secondary-50',
  onAccent: 'color-brand-primary-500', // text on an accent fill (gold takes ink)
  link: 'color-link',
  // text
  text: 'text-primary',
  body: 'text-body',
  muted: 'text-muted',
  faint: 'text-faint',
  // surfaces and lines
  page: 'page-bg',
  card: 'card-bg',
  inset: 'inset-bg',
  field: 'field-bg',
  border: 'card-border',
  borderLight: 'border-light',
  tableHeader: 'table-header-bg',
  onTableHeader: 'table-header-fg',
  // the neutral scale (document rules, lines and washes; n500 is the lightest text-safe step, 4.5:1+)
  n50: 'color-neutral-50',
  n100: 'color-neutral-100',
  n200: 'color-neutral-200',
  n300: 'color-neutral-300',
  n400: 'color-neutral-400',
  n500: 'color-neutral-500',
  n600: 'color-neutral-600',
  n700: 'color-neutral-700',
  // status (constant across brands, THEME_CLEANSPACE R3)
  success: 'color-semantic-success-500',
  successInk: 'color-semantic-success-700',
  successBg: 'color-semantic-success-50',
  warning: 'color-semantic-warning-500',
  warningInk: 'color-semantic-warning-700',
  warningBg: 'color-semantic-warning-50',
  danger: 'color-semantic-error-500',
  dangerInk: 'color-semantic-error-700',
  dangerBg: 'color-semantic-error-50',
};

// "rgba(24, 24, 27, 0.6)" / "#FFF" → a canonical lowercase value
const norm = (v) => v.replace(/\s+/g, ' ').replace(/\(\s+/g, '(').replace(/\s+\)/g, ')').trim().toLowerCase();

export function buildBrandJs(overrides = {}) {
  const byName = new Map(readCascade(overrides).map((r) => [r.name, r.resolved]));
  const errors = [];
  const colors = {};
  for (const [role, token] of Object.entries(ROLES)) {
    const v = byName.get(token);
    if (!v) { errors.push(`--${token} (role ${role}) is not in the theme cascade`); continue; }
    if (!/^#[0-9a-f]{3,8}$|^rgba?\(/i.test(v.trim())) { errors.push(`--${token} (role ${role}) resolves to "${v}", not a colour value`); continue; }
    colors[role] = norm(v);
  }
  const body = Object.entries(colors).map(([k, v]) => `  ${k}: '${v}',`).join('\n');
  const text = `// GENERATED by \`npm --prefix app run brand:js\` from the theme cascade (theme.css → the client theme →
// theme-flat.css → index.css :root). Do not edit: change the theme, then regenerate. test-design-system.mjs
// fails when this file no longer matches the cascade. For code that cannot read a CSS variable (document
// and email templates, canvas, generated SVG); everything else reads var(--token).
export const BRAND = Object.freeze({
${body}
});
`;
  return { text, errors, colors };
}

// The browser chrome colours are brand outputs too: the PWA manifest's theme/background colour and the
// <meta name="theme-color"> tint the phone's status bar and task switcher. Both follow `primary`.
const MANIFEST = path.join(APP, 'public', 'manifest.json');
const INDEX = path.join(APP, 'index.html');
export function chromeTargets(primary) {
  const raw = fs.readFileSync(MANIFEST, 'utf8');
  const manifest = raw.replace(/("(?:theme|background)_color"\s*:\s*")[^"]*(")/g, `$1${primary}$2`);
  const html = fs.readFileSync(INDEX, 'utf8').replace(/(<meta name="theme-color" content=")[^"]*(")/, `$1${primary}$2`);
  return [[MANIFEST, raw, manifest], [INDEX, fs.readFileSync(INDEX, 'utf8'), html]];
}

// Values a CSS variable cannot reach are re-drawn in the brand and written into the client theme's
// GENERATED block: an icon drawn in a data URI (the select chevron, in the theme's --color-neutral-400).
// The base theme defines none of them, so a client theme without a current block fails the gate.
export const CLIENT_THEME = path.join(APP, 'src', 'theme-cleanspace.css');
const GENERATED = /(\/\* ── GENERATED by `npm --prefix app run brand:js`[\s\S]*?\*\/)([\s\S]*?)(\n[ \t]*\/\* ── end GENERATED ── \*\/)/;
export function generatedDecls(byName) {
  const n400 = byName.get('color-neutral-400');
  if (!n400 || !/^#[0-9a-f]{6}$/i.test(n400.trim())) return { decls: null, error: `--color-neutral-400 resolves to "${n400}", not a #rrggbb colour` };
  const chevron = `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='%23${n400.trim().slice(1).toLowerCase()}' stroke-width='2'%3E%3Cpath d='M6 9l6 6 6-6'/%3E%3C/svg%3E")`;
  return { decls: [['icon-select-chevron', chevron]] };
}
export function themeTarget() {
  const raw = fs.readFileSync(CLIENT_THEME, 'utf8');
  const crlf = raw.includes('\r\n');
  const lf = raw.replace(/\r\n/g, '\n');
  if (!GENERATED.test(lf)) return { error: `${path.basename(CLIENT_THEME)} has no GENERATED block: add the "── GENERATED by \`npm --prefix app run brand:js\` …" and "── end GENERATED ──" comments at the end of its :root rule` };
  const { decls, error } = generatedDecls(new Map(readCascade().map((r) => [r.name, r.resolved])));
  if (error) return { error };
  const body = decls.map(([n, v]) => `\n  --${n}: ${v};`).join('');
  const next = lf.replace(GENERATED, (all, open, _old, close) => `${open}${body}${close}`);
  return { target: [CLIENT_THEME, raw, crlf ? next.replace(/\n/g, '\r\n') : next] };
}

/**
 * Every output this script writes, from the theme cascade as it is on disk now, as [file, before, after]
 * (tokens.generated.js, the manifest, index.html, the client theme's GENERATED block), plus the resolved
 * BRAND colours. `npm --prefix app run brand` calls it after writing the brand's palette into the theme.
 */
export function brandJsTargets() {
  const { text, errors, colors } = buildBrandJs();
  const theme = themeTarget();
  if (theme.error) errors.push(theme.error);
  if (errors.length) return { errors };
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  return { errors, colors, targets: [[OUT, cur, text], ...chromeTargets(colors.primary), theme.target] };
}

const invoked = path.resolve(process.argv[1] || '') === fileURLToPath(import.meta.url);
if (invoked) {
  const { errors, colors, targets } = brandJsTargets();
  if (errors.length) { console.error('brand-js:\n  ' + errors.join('\n  ')); process.exit(1); }
  const norm = (s) => s.replace(/\r\n/g, '\n');
  if (process.argv.includes('--check')) {
    const stale = targets.filter(([, before, after]) => norm(before) !== norm(after)).map(([file]) => path.relative(APP, file).split(path.sep).join('/'));
    if (stale.length) { console.error(`stale brand outputs: ${stale.join(', ')}. Run \`npm --prefix app run brand:js\` and commit them.`); process.exit(1); }
    console.log("brand-js: tokens.generated.js, manifest.json, index.html and the client theme's GENERATED block match the theme cascade");
  } else {
    fs.mkdirSync(path.dirname(OUT), { recursive: true });
    for (const [file, before, after] of targets) if (before !== after) fs.writeFileSync(file, after);
    console.log(`brand-js: wrote ${Object.keys(ROLES).length} roles to src/brand/tokens.generated.js; manifest + theme-color = ${colors.primary}; the client theme's GENERATED block (select chevron)`);
  }
}
