#!/usr/bin/env node
// design-system — regenerate the Clean Space design system from the code. ONE command:
//
//   npm --prefix app run design-system
//
// Writes:
//   app/design-system/tokens.json       the committed token snapshot (test-design-system.mjs
//                                       fails the build when the theme and this disagree)
//   app/design-system/dist/project/**   everything the Design System artifact serves:
//                                       tokens.json, components/bundle.css + bundle.js, the
//                                       hand-written content (brand book, component cards,
//                                       previews, cover) and guidelines/rules.md (the rule
//                                       registry rendered as the enforcement table)
//   app/design-system/dist/uploads/**   the icon SVGs, rendered through the Icon component
//
// dist/ is gitignored: it is rebuilt from source every time. Publishing it is a separate,
// deliberate step (see app/design-system/README.md), never automatic.
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { pathToFileURL } from 'node:url';
import { rolldown } from 'rolldown';
import { APP, DS, readJson, readCascade, readMediaOverrides, parseRules, readAppCss, buildTokens, enumerateRules } from './design-system-lib.mjs';
import { controlFamilies } from './control-families.mjs';

const DIST = path.join(DS, 'dist');
const OUT = path.join(DIST, 'project');
const config = readJson(path.join(DS, 'tokens.config.json'));
const comps = readJson(path.join(DS, 'components.json'));
const registry = readJson(path.join(DS, 'rules.json'));
const git = (...a) => { try { return execFileSync('git', a, { cwd: APP, encoding: 'utf8' }).trim(); } catch { return ''; } };

// ── tokens ───────────────────────────────────────────────────────────────────────────
const cascade = readCascade();
const css = readAppCss();
const { tokens, errors } = buildTokens(config, { cascade, rules: parseRules(css) });
if (errors.length) {
  console.error('design-system: the token config and the theme disagree:\n  - ' + errors.join('\n  - '));
  process.exit(1);
}
fs.writeFileSync(path.join(DS, 'tokens.json'), JSON.stringify(tokens, null, 2) + '\n');
fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(path.join(OUT, 'components'), { recursive: true });
const ref = `${git('rev-parse', '--abbrev-ref', 'HEAD') || 'HEAD'}@${git('rev-parse', '--short', 'HEAD') || 'unknown'}`;
const published = { ...tokens, meta: { ...tokens.meta, ref, synced: new Date().toISOString().slice(0, 10) } };
fs.writeFileSync(path.join(OUT, 'tokens.json'), JSON.stringify(published, null, 2) + '\n');

// ── bundle.css: the Poppins import, the recipe layer, then index.css verbatim ───────────
const lines = css.split('\n');
if (!/^@import url\('https:\/\/fonts\.googleapis\.com/.test(lines[0]) || !lines[1].includes('./theme.css') || !lines[3].includes('./theme-flat.css')) {
  console.error('design-system: index.css no longer opens with the font import + the three theme imports; update this generator.');
  process.exit(1);
}
const recipes = new Set(config.recipes);
const byFile = new Map();
for (const r of cascade) {
  if (!recipes.has(r.name) || r.file === 'index.css') continue; // index.css's own :root rides along verbatim
  if (!byFile.has(r.file)) byFile.set(r.file, []);
  byFile.get(r.file).push(`  --${r.name}: ${r.declared};`);
}
const bundleCss = `${lines[0]}
/* Clean Space: the app's stylesheet (app/src/index.css), shipped whole. Generated by
   app/scripts/design-system.mjs; never edit the published copy.
   Layering, exactly as the app composes it:
     tokens.css (generated from tokens.json)  = theme.css tokens + aliases, CleanSpace colour values, the flat rings
     :root below                               = the RECIPE layer tokens.json can't hold (gradients, glass, rgba mixes,
                                                 the flat treatment's "none" shadows, the --font alias), final cascade values
     everything after                          = index.css, verbatim: the component classes (.btn, .card, .badge, table, …) */
:root {
${[...byFile.entries()].map(([f, d]) => `  /* from ${f} */\n${d.join('\n')}`).join('\n\n')}
}
${readMediaOverrides().map((b) => `/* responsive token values, from ${b.file} */\n${b.media} {\n  :root {\n${b.decls.map(([n, v]) => `    --${n}: ${v};`).join('\n')}\n  }\n}`).join('\n')}
${lines.slice(4).join('\n')}`;
if (/<\/style/i.test(bundleCss)) { console.error('design-system: bundle.css would contain </style'); process.exit(1); }
fs.writeFileSync(path.join(OUT, 'components', 'bundle.css'), bundleCss);

// ── bundle.js: the shared components as ONE classic script on window.CleanSpace ─────────
const REACT_NAMES = ['Children', 'Component', 'Fragment', 'Profiler', 'PureComponent', 'StrictMode', 'Suspense', 'cloneElement',
  'createContext', 'createElement', 'createRef', 'forwardRef', 'isValidElement', 'lazy', 'memo', 'startTransition', 'useCallback',
  'useContext', 'useDebugValue', 'useDeferredValue', 'useEffect', 'useId', 'useImperativeHandle', 'useInsertionEffect',
  'useLayoutEffect', 'useMemo', 'useReducer', 'useRef', 'useState', 'useSyncExternalStore', 'useTransition'];
const SHIMS = {
  react: `var R = window.React; export default R; export var ${REACT_NAMES.map((n) => `${n} = R.${n}`).join(', ')};`,
  'react-dom': 'var D = window.ReactDOM; export default D; export var createPortal = D.createPortal, flushSync = D.flushSync;',
  'react/jsx-runtime': `var R = window.React; export var Fragment = R.Fragment;
export function jsx(type, props, key) { return R.createElement(type, key === undefined ? props : Object.assign({}, props, { key: key })); }
export var jsxs = jsx;`,
  'react-router-dom': `var R = window.React;
function hrefOf(to) { if (typeof to === 'string') return to; if (to && typeof to === 'object') return (to.pathname || '') + (to.search || '') + (to.hash || ''); return '#'; }
export var Link = R.forwardRef(function Link(props, ref) {
  var p = Object.assign({}, props); var onClick = p.onClick; var href = hrefOf(p.to);
  ['to', 'state', 'replace', 'reloadDocument', 'preventScrollReset', 'relative', 'viewTransition', 'discover', 'prefetch'].forEach(function (k) { delete p[k]; });
  p.ref = ref; p.href = href; p.onClick = function (e) { if (onClick) onClick(e); e.preventDefault(); };
  return R.createElement('a', p);
});
export function useNavigate() { return function () {}; }
export function useLocation() { return { pathname: '/', search: '', hash: '', state: null, key: 'default' }; }`,
};
const tmp = path.join(DIST, 'tmp');
fs.mkdirSync(tmp, { recursive: true });
const abs = (f) => JSON.stringify(path.join(APP, f).split(path.sep).join('/'));
const entry = path.join(tmp, 'entry.js');
fs.writeFileSync(entry, [
  ...comps.exports.map((e, i) => (e.named ? `import { ${e.name} as x${i} } from ${abs(e.from)};` : `import x${i} from ${abs(e.from)};`)),
  `var g = window; g.${comps.namespace} = Object.assign(g.${comps.namespace} || {}, { ${comps.exports.map((e, i) => `${e.name}: x${i}`).join(', ')} });`,
].join('\n'));
const shimPlugin = {
  name: 'design-system-globals',
  resolveId: (id) => (Object.hasOwn(SHIMS, id) ? '\0shim:' + id : null),
  load: (id) => (id.startsWith('\0shim:') ? SHIMS[id.slice(6)] : null),
};
const web = await rolldown({ input: entry, platform: 'browser', cwd: APP, transform: { jsx: 'react-jsx', define: { 'process.env.NODE_ENV': '"production"' } }, plugins: [shimPlugin], logLevel: 'warn' });
await web.write({ file: path.join(tmp, 'bundle.js'), format: 'iife', minify: true });
const code = fs.readFileSync(path.join(tmp, 'bundle.js'), 'utf8').trim();
for (const [re, what] of [[/<\/script/i, '</script'], [/<!--/, '<!--'], [/\beval\s*\(/, 'eval('], [/new Function\s*\(/, 'new Function('], [/\bimport\s*\(/, 'import('], [/^\s*import\s/m, 'an import statement']]) {
  if (re.test(code)) { console.error(`design-system: bundle.js contains ${what}`); process.exit(1); }
}
const header = '/* @ds-bundle: ' + JSON.stringify({ format: 4, namespace: comps.namespace, components: comps.cards.map((name) => ({ name })) }) + ' */';
fs.writeFileSync(path.join(OUT, 'components', 'bundle.js'), header + '\n' + code + '\n');

// ── icons: every glyph of the Icon registry, rendered through the component ────────────
const iconSrc = fs.readFileSync(path.join(APP, 'src/components/Icon.jsx'), 'utf8');
const block = iconSrc.slice(iconSrc.indexOf('const paths = {'), iconSrc.indexOf('\n};', iconSrc.indexOf('const paths = {')));
const iconNames = [...block.matchAll(/^ {2}([A-Za-z][A-Za-z0-9]*)\s*:/gm)].map((m) => m[1]);
const nodeEntry = path.join(tmp, 'icons-entry.jsx');
fs.writeFileSync(nodeEntry, `import Icon from ${abs('src/components/Icon.jsx')};
import { renderToStaticMarkup } from 'react-dom/server';
import { createElement } from 'react';
export const render = (name) => renderToStaticMarkup(createElement(Icon, { name, size: 24 }));`);
const node = await rolldown({ input: nodeEntry, platform: 'node', cwd: APP, transform: { jsx: 'react-jsx', define: { 'process.env.NODE_ENV': '"production"' } }, logLevel: 'warn' });
await node.write({ file: path.join(tmp, 'icons.mjs'), format: 'esm' });
const { render } = await import(pathToFileURL(path.join(tmp, 'icons.mjs')).href);
const iconDir = path.join(DIST, 'uploads', 'Icons');
fs.mkdirSync(iconDir, { recursive: true });
for (const n of iconNames) {
  const svg = render(n);
  if (!svg) { console.error(`design-system: Icon "${n}" rendered nothing`); process.exit(1); }
  fs.writeFileSync(path.join(iconDir, `${n}.svg`), svg.replace('<svg ', '<svg xmlns="http://www.w3.org/2000/svg" ').replace(/ class=""/, '').replace(/ aria-hidden="true"/, '') + '\n');
}
const assets = readJson(path.join(DS, 'assets.json'));
const uploaded = new Set(Object.keys(assets.Icons || {}).map((f) => f.replace(/\.svg$/, '')));
const newIcons = iconNames.filter((n) => !uploaded.has(n));
const goneIcons = [...uploaded].filter((n) => !iconNames.includes(n));
fs.rmSync(tmp, { recursive: true, force: true });

// ── content: the hand-written brand book, cards, previews, cover ────────────────────────
fs.cpSync(path.join(DS, 'content'), OUT, { recursive: true });

// ── guidelines/rules.md: the registry, as the enforcement table ─────────────────────────
const LABEL = { gated: 'Gated', checked: 'Checked', construction: 'By construction', review: 'Review only', superseded: 'Superseded' };
const byId = new Map(registry.rules.map((r) => [r.id, r]));
const enumerated = enumerateRules();
const counts = Object.fromEntries(Object.keys(LABEL).map((k) => [k, registry.rules.filter((r) => r.status === k).length]));
const held = (r) => {
  if (r.status === 'superseded') return `Superseded by ${r.supersededBy.map((id) => `${byId.get(id)?.source.replace(/^app\/src\//, '') ?? ''} ${byId.get(id)?.ref ?? id}`.trim()).join(', ')}`;
  const checks = (r.checks || []).map((c) => `\`${c}\``).join(', ');
  return `${LABEL[r.status]}${r.coverage === 'partial' ? ' (partly)' : ''}${checks ? `: ${checks}` : ''}`;
};
const esc = (s) => String(s || '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
let md = `# Rules and enforcement

Every numbered rule in UI_RULES.md, THEME_CLEANSPACE.md, STYLING.md and STRUCTURE.md, with what holds it today. The table is generated from \`app/design-system/rules.json\`; the build fails when a rule is added, renamed or removed without being classified here.

- **Gated**: CI fails when the rule is broken.
- **Checked**: a check exists, but CI doesn't run it yet.
- **By construction**: holds when you use the shared class or component; nothing fails if you bypass it.
- **Review only**: held by people reading the change.
- **Superseded**: replaced by a later rule; kept for history.

${enumerated.length} rules: ${Object.entries(counts).map(([k, n]) => `${n} ${LABEL[k].toLowerCase()}`).join(', ')}. Classified ${registry.classified} (${registry.level}).
`;
for (const area of registry.areas) {
  const rows = registry.rules.filter((r) => r.area === area.id);
  if (!rows.length) continue;
  md += `\n## ${area.title}\n\n| Rule | Held by | Note |\n|---|---|---|\n`;
  for (const r of rows) md += `| ${esc(r.source.replace(/^app\/src\//, '').replace(/\.md$/, ''))} ${esc(r.ref)}: ${esc(r.title)} | ${esc(held(r))} | ${esc(r.note)} |\n`;
}
fs.mkdirSync(path.join(OUT, 'guidelines'), { recursive: true });
fs.writeFileSync(path.join(OUT, 'guidelines', 'rules.md'), md);

// ── guidelines/controls.md: the kit and the control ledger (UI_RULES §128) ─────────────────
const ledger = readJson(path.join(DS, 'controls.json'));
const fams = controlFamilies(path.join(APP, 'src'));
const used = (f) => fams.get(f)?.n ?? 0;
const kitTotal = Object.keys(ledger.kit).reduce((s, k) => s + used(k), 0);
const allTotal = [...fams.values()].reduce((s, F) => s + F.n, 0);
let cm = `# Controls

Every clickable control in the app is a kit control or is written down here. The page is generated from \`app/design-system/controls.json\` and the live source (UI_RULES §128); \`test-control-ledger.mjs\` fails CI on a family nobody classified.

${allTotal} controls in ${fams.size} families. The kit's ${Object.keys(ledger.kit).length} classes hold ${kitTotal}; ${Object.keys(ledger.families).length} families are classified below.

## The kit

| Class | In use | What it is |
|---|---|---|
`;
for (const [cls, what] of Object.entries(ledger.kit)) cm += `| \`${cls}\` | ${used(cls)} | ${esc(what)} |\n`;
const ROLE_TITLE = { row: 'Rows', card: 'Cards and tiles', nav: 'Navigation chrome', variant: 'Kit variants', exception: 'Exceptions' };
for (const [role, title] of Object.entries(ROLE_TITLE)) {
  const rows = Object.entries(ledger.families).filter(([, e]) => e.role === role);
  if (!rows.length) continue;
  cm += `\n## ${title}\n\n${esc(ledger.roles[role])}\n\n| Family | In use | Why |\n|---|---|---|\n`;
  for (const [f, e] of rows) cm += `| \`${esc(f)}\` | ${used(f)} | ${esc(e.why)} |\n`;
}
fs.writeFileSync(path.join(OUT, 'guidelines', 'controls.md'), cm);

// ── summary ──────────────────────────────────────────────────────────────────────────
const files = [];
(function walk(d) { for (const f of fs.readdirSync(d)) { const p = path.join(d, f); if (fs.statSync(p).isDirectory()) walk(p); else files.push(p); } })(OUT);
console.log(`design-system: ${files.length} files in ${path.relative(APP, OUT)} (${ref})`);
console.log(`  tokens: ${tokens.color.tokens.length} colours, ${Object.keys(config.families).length} more families, ${tokens.type.groups.reduce((a, g) => a + g.styles.length, 0)} text styles`);
console.log(`  bundle: ${comps.exports.length} exports, ${comps.cards.length} cards · ${iconNames.length} icons rendered`);
console.log(`  rules:  ${enumerated.length} enumerated · ${Object.entries(counts).map(([k, n]) => `${k} ${n}`).join(' · ')}`);
console.log(`  controls: ${allTotal} in ${fams.size} families · kit ${Object.keys(ledger.kit).length} classes (${kitTotal}) · classified ${Object.keys(ledger.families).length}`);
if (newIcons.length) console.log(`  ⚠ icons not yet uploaded to the artifact: ${newIcons.join(', ')}`);
if (goneIcons.length) console.log(`  ⚠ uploaded icons no longer in Icon.jsx: ${goneIcons.join(', ')}`);
console.log('  publish: see app/design-system/README.md ("Publishing"); the lib/ React files and the uploads already on the artifact are kept.');
